name: Deploy on Server Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-on-prod:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build app
        run: |
          CI=false npm run build || { echo 'Build failed'; exit 1; }

      - name: List directory contents
        run: ls -l

      # - name: Verify build output
      #   run: ls -l ./build/

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./build/
          target: ~/portfolio
          port: 22
          debug: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/portfolio
            pm2 reload pm2.deploy.json
