name: Deploy on Server Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-on-prod:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repos
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build app
        run: CI=false npm run build
      
      - name: Copy build files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          password: ${{ secrets.PASSWORD_DEV }}
          source: './build/' # Transférer uniquement le dossier build
          target: ~/portfolio # Répertoire cible aligné avec les étapes suivantes
      
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          password: ${{ secrets.PASSWORD_DEV }}
          script: |            
            cd ~/portfolio
            pm2 reload pm2.deploy.json
